name = "cheeksunseen"
main = "server/src/index.js"
compatibility_date = "2026-10-06"

[assets]
directory = "./web"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "cheeksunseen-db"
database_id = "f759a5dd-5a48-4c00-89de-08b46b948fe6"
migrations_dir = "./migrations"
